use_frameworks!

platform :ios, '9.0'

target 'LKDLNAModule_Example' do
  pod 'LKDLNAModule', :path => '../'
  pod 'LKMacroCategoryModule', :path => '../../LKMacroCategoryModule'

  target 'LKDLNAModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
